spring:
  application:
    name: bizflow-gateway
  cloud:
    gateway:
      default-filters: []
      routes:
        - id: auth-service
          uri: "http://auth-service:8081/"
          predicates:
            - Path=/api/auth/**
        - id: user-service
          uri: "http://user-service:8084/"
          predicates:
            - Path=/api/users/**
        - id: product-service
          uri: "http://product-service:8082/"
          predicates:
            - Path=/api/products/**
        - id: inventory-service
          uri: "http://inventory-service:8085/"
          predicates:
            - Path=/api/inventory/**
        - id: order-service
          uri: "http://order-service:8083/"
          predicates:
            - Path=/api/orders/**
        - id: customer-service
          uri: "http://customer-service:8086/"
          predicates:
            - Path=/api/customers/**
        - id: promotion-service
          uri: "http://promotion-service:8087/"
          predicates:
            - Path=/api/promotions/**
        - id: payment-service
          uri: "http://payment-service:8088/"
          predicates:
            - Path=/api/payments/**
        - id: report-service
          uri: "http://report-service:8089/"
          predicates:
            - Path=/api/reports/**
        - id: ai-service
          uri: "http://ai_service:5000/"
          predicates:
            - Path=/ai/**
        - id: fcm-service
          uri: "http://fcm-service:8091/"
          predicates:
            - Path=/api/fcm/**

server:
  port: 8000
  servlet:
    context-path: /

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    com.example.gateway: DEBUG
